-- 02_sales_performance.sql
-- Retail Sales SQL Project
-- Sales Performance Analysis


-- 1. Overall sales performance
-- Measures the total number of transactions, total revenue,
-- average transaction value, minimum transaction value,
-- and maximum transaction value.

SELECT
    COUNT(*) AS total_transactions,
    SUM(Total_Amount) AS total_revenue,
    AVG(Total_Amount) AS average_transaction_value,
    MIN(Total_Amount) AS minimum_transaction_value,
    MAX(Total_Amount) AS maximum_transaction_value
FROM retail_sales_dataset;


-- 2. Revenue by product category
-- Determines which product categories generate the most revenue.

SELECT
    Product_Category,
    SUM(Total_Amount) AS total_revenue
FROM retail_sales_dataset
GROUP BY Product_Category
ORDER BY total_revenue DESC;


-- 3. Compare sales performance across product categories
-- Compares transaction volume, quantity sold, revenue,
-- and average transaction value.

SELECT
    Product_Category,
    COUNT(*) AS total_transactions,
    SUM(CAST(Quantity AS INT)) AS total_quantity_sold,
    SUM(Total_Amount) AS total_revenue,
    AVG(Total_Amount) AS average_transaction_value
FROM retail_sales_dataset
GROUP BY Product_Category
ORDER BY total_revenue DESC;


-- 4. Average price per unit by product category
-- Compares the average unit price between product categories.

SELECT
    Product_Category,
    AVG(Price_per_Unit) AS average_price_per_unit
FROM retail_sales_dataset
GROUP BY Product_Category
ORDER BY average_price_per_unit DESC;


-- 5. Revenue generated per unit by product category
-- Compares total revenue relative to the number of units sold.

SELECT
    Product_Category,
    SUM(Total_Amount) AS total_revenue,
    SUM(CAST(Quantity AS INT)) AS total_quantity_sold,
    SUM(Total_Amount) / SUM(CAST(Quantity AS INT)) AS revenue_per_unit
FROM retail_sales_dataset
GROUP BY Product_Category
ORDER BY revenue_per_unit DESC;


-- 6. Identify transactions above the overall average transaction value
-- Determines how many transactions have a value greater
-- than the overall average.

SELECT
    COUNT(*) AS transactions_above_average
FROM retail_sales_dataset
WHERE Total_Amount >
      (
          SELECT AVG(Total_Amount)
          FROM retail_sales_dataset
      );


-- 7. Calculate the percentage of transactions above the average
-- Places the number of above-average transactions in context
-- relative to all transactions.

SELECT
    COUNT(*) AS transactions_above_average,
    COUNT(*) * 100.0 /
        (SELECT COUNT(*) FROM retail_sales_dataset)
        AS percentage_of_transactions
FROM retail_sales_dataset
WHERE Total_Amount >
      (
          SELECT AVG(Total_Amount)
          FROM retail_sales_dataset
      );


-- 8. Calculate revenue generated by above-average transactions
-- Measures how much of total revenue comes from transactions
-- whose value exceeds the overall average.

SELECT
    SUM(Total_Amount) AS revenue_from_above_average_transactions,
    SUM(Total_Amount) * 100.0 /
        (SELECT SUM(Total_Amount) FROM retail_sales_dataset)
        AS percentage_of_total_revenue
FROM retail_sales_dataset
WHERE Total_Amount >
      (
          SELECT AVG(Total_Amount)
          FROM retail_sales_dataset
      );


-- 9. Combine transaction and revenue concentration
-- Summarizes the proportion of transactions above the overall
-- average and the proportion of total revenue they generate.

SELECT
    COUNT(*) AS transactions_above_average,
    COUNT(*) * 100.0 /
        (SELECT COUNT(*) FROM retail_sales_dataset)
        AS percentage_of_transactions,
    SUM(Total_Amount) AS revenue_generated,
    SUM(Total_Amount) * 100.0 /
        (SELECT SUM(Total_Amount) FROM retail_sales_dataset)
        AS percentage_of_total_revenue
FROM retail_sales_dataset
WHERE Total_Amount >
      (
          SELECT AVG(Total_Amount)
          FROM retail_sales_dataset
      );
